"""Make assessment_id required in voice_analyses

Revision ID: 54299872506e
Revises: 4d98caa198f4
Create Date: 2025-10-02 16:47:17.396147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54299872506e'
down_revision: Union[str, None] = '4d98caa198f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Report orphaned voice_analyses records (for monitoring)
    connection = op.get_bind()
    result = connection.execute(sa.text("""
        SELECT COUNT(*) FROM voice_analyses WHERE assessment_id IS NULL
    """))
    orphan_count = result.scalar()
    print(f"Found {orphan_count} orphaned voice_analyses records (will be deleted)")
    
    # Step 2: Delete orphaned records (safe for test data)
    # These are voice analyses that were created standalone during testing
    op.execute("""
        DELETE FROM voice_analyses WHERE assessment_id IS NULL
    """)
    print("Orphaned records deleted successfully")
    
    # Step 3: Update assessments table
    op.alter_column('assessments', 'recommendations',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('assessments', 'completed_at')
    
    # Step 4: Make assessment_id NOT NULL (now safe after deletion)
    op.alter_column('voice_analyses', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='Required: Links voice analysis to its parent assessment')
    op.alter_column('voice_analyses', 'audio_features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('voice_analyses', 'keywords',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('voice_analyses', 'psychological_markers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('voice_analyses', 'normalized_features',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index('idx_voice_analyses_assessment', table_name='voice_analyses')
    op.drop_index('idx_voice_analyses_created_at', table_name='voice_analyses')
    op.drop_index('idx_voice_analyses_dominant_emotion', table_name='voice_analyses')
    op.drop_index('idx_voice_analyses_processing_status', table_name='voice_analyses')
    op.create_index(op.f('ix_voice_analyses_assessment_id'), 'voice_analyses', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_voice_analyses_created_at'), 'voice_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_voice_analyses_dominant_emotion'), 'voice_analyses', ['dominant_emotion'], unique=False)
    op.create_index(op.f('ix_voice_analyses_student_id'), 'voice_analyses', ['student_id'], unique=False)
    op.drop_constraint('fk_voice_analyses_assessment', 'voice_analyses', type_='foreignkey')
    op.create_foreign_key(None, 'voice_analyses', 'assessments', ['assessment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'voice_analyses', type_='foreignkey')
    op.create_foreign_key('fk_voice_analyses_assessment', 'voice_analyses', 'assessments', ['assessment_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_voice_analyses_student_id'), table_name='voice_analyses')
    op.drop_index(op.f('ix_voice_analyses_dominant_emotion'), table_name='voice_analyses')
    op.drop_index(op.f('ix_voice_analyses_created_at'), table_name='voice_analyses')
    op.drop_index(op.f('ix_voice_analyses_assessment_id'), table_name='voice_analyses')
    op.create_index('idx_voice_analyses_processing_status', 'voice_analyses', ['processing_status'], unique=False)
    op.create_index('idx_voice_analyses_dominant_emotion', 'voice_analyses', ['dominant_emotion'], unique=False)
    op.create_index('idx_voice_analyses_created_at', 'voice_analyses', ['created_at'], unique=False)
    op.create_index('idx_voice_analyses_assessment', 'voice_analyses', ['assessment_id'], unique=False)
    op.alter_column('voice_analyses', 'normalized_features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('voice_analyses', 'psychological_markers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('voice_analyses', 'keywords',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('voice_analyses', 'audio_features',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('voice_analyses', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='Required: Links voice analysis to its parent assessment')
    op.add_column('assessments', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.alter_column('assessments', 'recommendations',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
